services:
  - type: worker
    name: telegram-protection-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        fromSecret: true
      - key: CHAT_ID
        fromSecret: true
