services:
  - type: worker
    name: telegram-group-protection-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: telegram_bot_db
          property: connectionString
      - key: OWNER_ID
        sync: false
      - key: OWNER_USERNAME
        sync: false
